# Copyright (c) 2018 Huawei Technologies Co., Ltd. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Download mysql-apt-config
  get_url:
    url:  https://dev.mysql.com/get/mysql-apt-config_0.8.6-1_all.deb
    dest: /tmp/mysql-apt-config_0.8.6-1_all.deb

- name: install mysql-apt-config
  apt: deb="/tmp/mysql-apt-config_0.8.6-1_all.deb"
  sudo: true

- name: Update repositories cache and install libmysqlclient-dev package
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - libmysqlclient-dev
    - libapache2-mod-wsgi

- name: configure opensds global info
  shell: |
    cat > opensds.conf <<OPENSDS_GLOABL_CONFIG_DOC
    [osdslet]
    api_endpoint = {{ controller_endpoint }}
    graceful = True
    log_file = {{ controller_log_file }}
    socket_order = inc
    auth_strategy = {{ opensds_auth_strategy }}

    [database]
    endpoint = {{ db_endpoint }}
    driver = {{ db_driver }}
  args:
    chdir: "{{ opensds_config_dir }}"
  ignore_errors: yes

# - name: install keystone
#   shell: "{{ item }}"
#   with_items:
#     - bash ./script/keystone.sh install
#   when: opensds_auth_strategy == "keystone"
#   become: yes
