---
- name: deploy  opensds ctl
  hosts: docks
  remote_user: root
  vars_files:
    - group_vars/common.yml
    - group_vars/auth.yml
    - group_vars/osdsdb.yml
    - group_vars/osdslet.yml
    - group_vars/osdsdock.yml
  gather_facts: false
  become: True
  roles:
    - osdsdock
