# Default values for opensds csi plugin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image: opensdsio/csiplugin:latest
# ImagePullPolicy: valid values are "IfNotPresent", "Never", and "Always"
imagePullPolicy: IfNotPresent
# ImageRestartPolicy: valid values are "Never", and "Always"
imageRestartPolicy: Never
# Please modify opensdsEndpoint field in real environment
opensdsEndpoint: http://127.0.0.1:50040
